# Generated by Django 6.0.6 on 2026-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_serviceinquiry_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarlead',
            name='calculation_type',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='category',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='input_value',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='monthly_savings',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='name',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='recommended_kw',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='state',
        ),
        migrations.AddField(
            model_name='solarlead',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='monthly_bill_or_units',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='solar_capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solarlead',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
