# Generated by Django 6.0.6 on 2026-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_solarlead_calculation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarlead',
            name='monthly_bill_or_units',
        ),
        migrations.RemoveField(
            model_name='solarlead',
            name='solar_capacity',
        ),
        migrations.AddField(
            model_name='solarlead',
            name='calculation_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='input_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solarlead',
            name='unit_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
